---
dotfiles:
  - .ackrc
  - .bash
  - .bash_profile
  - .emacs.d
  - .ghci
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gitk
  - .gvimrc
  - .hammerspoon
  - .hgrc
  - .inputrc
  - .npmrc
  - .rdebugrc
  - .rspec
  - .screenrc
  - .tmux.conf
  - .vim
  - .zsh
  - .zshenv
  - .zshrc
