---

# `defaults read` commands fail with exit status 255 if invoked improperly, but
# 1 for non-fatal problems, such as missing values.

- name: defaults | register existing values
  command: defaults {{ item.read }}
  register: existing_defaults
  loop: '{{osx_defaults}}'
  failed_when: existing_defaults.rc > 1
  changed_when: false
  check_mode: no
  loop_control:
    label: "{{item.description}}"

- name: defaults | show existing_defaults
  debug:
    var: existing_defaults
    verbosity: 2

- name: defaults | update defaults
  command: defaults {{ item.0.write }}
  when: item.1.stdout is not search(item.0.expected)
  loop:
    '{{ osx_defaults | zip(existing_defaults.results) | list }}'
  loop_control:
    label: "{{item.0.description}}"
