---
- hosts: localhost
  roles:
    - { role: iterm, tags: iterm }
    - { role: dotfiles, tags: dotfiles }
    - { role: shell, tags: shell }
    - { role: vim, tags: vim }
    - { role: ssh, tags: ssh }
    - { role: misc, tags: misc }
  vars:
    command_t_bundle: ext.bundle
    install_deoplete_extensions: true
    install_masochist_vim_dependencies: true
    update_vim_bundle: true
