---
- name: Create backup directory
  file: path=~/.backups state=directory

- name: Backup originals
  command:
    mv ~/{{ item }} ~/.backups/
    creates=~/.backups/{{ item }}
    removes=~/{{ item }}
  with_items: dotfiles

- name: Symlink dotfiles
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  with_items: dotfiles
