---
- name: dotfiles | check for decrypted files
  command: vendor/git-cipher/bin/git-cipher status
  failed_when: no
  register: cipher_check

- name: dotfiles | print encrypted file status
  set_fact:
    noop_fact: 1
  with_items:
    - "{{ cipher_check.stdout.split('\n') }}"
  when: not cipher_check.rc == 0
  changed_when: not cipher_check.rc == 0
