---
- name: Symlink dotfiles
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .ackrc
    - .bash
    - .bash_profile
    - .gitattributes
    - .gitconfig
    - .gitignore
    - .gitk
    - .gvimrc
    - .hgrc
    - .inputrc
    - .rdebugrc
    - .rspec
    - .screenrc
    - .shells
    - .slate.js
    - .tmux.conf
    - .vim
    - .zsh
    - .zshrc
