---
- name: dotfiles | check for decrypted files
  command: vendor/git-cipher/bin/git-cipher status
  failed_when: no
  register: cipher_check

- name: dotfiles | print encrypted file status
  set_fact:
    noop_fact: 1
  with_items:
    - "{{ cipher_check.stdout.split('\n') }}"
  when: not cipher_check.rc == 0
  changed_when: not cipher_check.rc == 0

# This is a bit random having this in here, but it's a dependency of our
# Hammerspoon set-up.
# - name: dotfiles | set up karabiner-sudoers
#   template: dest=/private/etc/sudoers.d/karabiner-sudoers src=karabiner-sudoers
#   become: !!bool yes

# Note some nasty dependencies here between creating the symlinks (eg.
# effectively creating ~/mutt/config/) and then templating into it (eg.
# ~/.mutt/config/settings.mutt).
- name: dotfiles | create templates
  template: dest={{ ansible_env.HOME }}/{{ item }}
            mode={{ '0755' if item.endswith('.sh') else '0644' }}
            src={{ item }}
  loop: '{{dotfile_templates}}'
