---
- name: dotfiles | check for decrypted files
  command: vendor/git-cipher/bin/git-cipher status
  failed_when: no
  register: cipher_check

- name: dotfiles | print encrypted file status
  set_fact:
    noop_fact: 1
  with_items:
    - "{{ cipher_check.stdout.split('\n') }}"
  when: not cipher_check.rc == 0
  changed_when: not cipher_check.rc == 0

- name: dotfiles | test Karabiner generator
  command: '{{ ansible_env.PWD }}/roles/dotfiles/support/karabiner-test.js'
  when: use_karabiner

- name: dotfiles | prepare Karabiner config
  command: '{{ ansible_env.PWD }}/roles/dotfiles/support/karabiner.js'
  register: karabiner_config
  check_mode: no
  when: use_karabiner

- name: dotfiles | show karabiner_config
  debug:
    var: karabiner_config
    verbosity: 2

# This is a bit random having this in here, but it's a dependency of our
# Hammerspoon set-up.
- name: dotfiles | set up karabiner-sudoers
  template: dest=/private/etc/sudoers.d/karabiner-sudoers src=karabiner-sudoers
  become: !!bool yes
  when: use_karabiner

# Note some nasty dependencies here between creating the symlinks (eg.
# effectively creating ~/mutt/config/) and then templating into it (eg.
# ~/.mutt/config/settings.mutt).
- name: dotfiles | create templates
  template: dest={{ ansible_env.HOME }}/{{ item }}
            mode={{ '0755' if item.endswith('.sh') else '0644' }}
            src={{ item }}
  loop: '{{dotfile_templates}}'

# Override insanely low open file limits on macOS.
- name: dotfiles | copy maxfiles.zsh
  copy: dest=~/.zshenv.d/maxfiles.zsh src=maxfiles.zsh
  when: ansible_os_family == "Darwin"

# Make some directories required by configuration in the dotfiles; these should
# probably be separate roles.
- name: dotfiles | create auxiliary directories
  file: path={{ item }} state=directory
  loop:
    # mbsync will die on first sync without this:
    - ~/.mail

- name: dotfiles | make ~/code
  file: path=~/code state=directory
  when: identity == "wincent"

- name: dotfiles | link ~/code/.editorconfig
  template: dest={{ ansible_env.HOME }}/code/.editorconfig
            src=code/.editorconfig
  when: identity == "wincent"
