---
- name: keyboards | ensure Karabiner support directory exists
  file: path="~/Library/Application Support/Karabiner" state=directory

- name: keyboards | copy Karabiner private.xml files
  copy: dest="~/Library/Application Support/Karabiner/{{ item }}"
        src={{ ansible_env.PWD }}/roles/keyboard/files/{{ item }}
  with_items:
    - modifiers.xml
    - private.xml
    - realforce.xml
    - spacefn.xml
    - terminal.xml
    - yubikey.xml
