---
- name: vim | configure Command-T
  command:
    ruby extconf.rb
    creates={{ command_t_base }}/ruby/command-t/ext/command-t/Makefile
    chdir={{ command_t_base }}/ruby/command-t/ext/command-t

- name: vim | compile Command-T
  command:
    make
    creates={{ command_t_base }}/ruby/command-t/ext/command-t/{{ command_t_bundle }}
    chdir={{ command_t_base }}/ruby/command-t/ext/command-t

- name: vim | check languageclient
  stat: path={{ language_client_base }}/bin/languageclient
  register: language_client_status

- name: vim | build LanguageClient-neovim
  command:
    ./install.sh
    chdir={{ language_client_base }}
  when: (language_client_status is not defined or not language_client_status.stat.exists) or (vim_bundle_update is defined and vim_bundle_update.changed)

- name: vim | create or update spell file
  command:
    vim -u NONE -N -c 'mkspell! {{ spellfile }} | quit'
    creates={{ spellfile }}.spl
