---
- name: vim | configure Command-T
  command:
    ruby extconf.rb
    creates={{ command_t_base }}/ruby/command-t/Makefile
    chdir={{ command_t_base }}/ruby/command-t

- name: vim | compile Command-T
  command:
    make
    creates={{ command_t_base }}/ruby/command-t/{{ command_t_bundle }}
    chdir={{ command_t_base }}/ruby/command-t

- name: vim | install YouCompleteMe
  command: ./install.sh chdir={{ you_complete_me_base }}
