---
- name: vim | configure Command-T
  command:
    ruby extconf.rb
    creates={{ command_t_base }}/ruby/command-t/ext/command-t/Makefile
    chdir={{ command_t_base }}/ruby/command-t/ext/command-t

- name: vim | compile Command-T
  command:
    make
    creates={{ command_t_base }}/ruby/command-t/ext/command-t/{{ command_t_bundle }}
    chdir={{ command_t_base }}/ruby/command-t/ext/command-t

- name: vim | build LanguageClient-neovim
  command:
    ./install.sh
    chdir={{ language_client_base }}
    creates={{ language_client_base }}/bin/languageclient

- name: vim | create or update spell file
  command:
    vim -u NONE -N -c 'mkspell! {{ spellfile }} | quit'
    creates={{ spellfile }}.spl
