---
# Optional really; just allows us to release updates to deoplete sorter
# extension dependency (commandt.score).
- name: vim | install twine via pip3
  pip: executable=pip3 name=twine

- name: vim | install commandt.score via pip3
  pip: executable=pip3 name=commandt.score

- name: vim | install msgpack via pip3
  pip: executable=pip3 name=msgpack

# TODO: should probably upgrade from time to time as well
# pip3 install --upgrade pynvim
# yarn global add neovim (upgrades)
