# Default keymaps: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap.toml

[[manager.prepend_keymap]]
# Mnemonic: "[T]oggle preview"
on   = "T"
run  = "plugin --sync hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
# Mnemonic: "[F]ull-size preview"
on   = "F"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
# (Normally, "Seek down 5 units in the preview".)
# See: https://yazi-rs.github.io/docs/tips#parent-arrow
on  = "J"
run = "plugin --sync parent-arrow --args=1"
desc = "Navigate down in the parent directory without changing focus"

[[manager.prepend_keymap]]
# (Normally, "Seek up 5 units in the preview".)
# See: https://yazi-rs.github.io/docs/tips#parent-arrow
on  = "K"
run = "plugin --sync parent-arrow --args=-1"
desc = "Navigate up in the parent directory without changing focus"
