# Default keymaps: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap.toml

[[manager.prepend_keymap]]
# Mnemonic: "[T]oggle preview"
on   = "T"
run  = "plugin --sync hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
# Mnemonic: "[F]ull-size preview"
on   = "F"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"
