---
- name: misc | ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/Archives
    - ~/Local

- name: misc | touch ~/mbox
  file: path=~/mbox state=touch

- name: misc | hide ~/mbox
  command: chflags hidden ~/mbox
