---
- name: misc | touch ~/mbox
  file: path=~/mbox state=touch

- name: misc | hide items
  command: chflags hidden {{ item }}
  loop:
    - ~/mbox

- name: misc | install prefnerd
  gem: name=prefnerd user_install=yes
