---
# We only link these ones if they don't already exist;
# once created, Hammerspoon manages the links.
- name: iterm | set up switchable symbolic links
  file:
    dest="~/Library/Application Support/iTerm2/DynamicProfiles/{{ item.dest }}"
    src="~/Library/Application Support/iTerm2/Sources/{{ item.src }}"
    state=link
  loop: '{{ iterm_dynamic_profiles.retina }}'
  loop_control:
    index_var: index
    label: '{{ item.dest }}@ -> {{ item.src }}'
  when: not dynamic_profiles_stat_info.results[index].stat.exists
