# Based on: https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

name: ci

on:
  push:
    branches: [main, next, pu]
  pull_request:
    branches: [main, next, pu]

jobs:

  check-lockfile:
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          # ******************************************************************
          # * NOTE: Keep these patterns up-to-date with bin/{check-,}format. *
          # ******************************************************************
          args: --list-different "**/*.{js,json,md,ts}" "*.{md,ts}"

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # *************************************************************
          # * NOTE: Keep this list up-to-date with bin/{check-,}format. *
          # *************************************************************
          args: --check aspects/dotfiles/.hammerspoon aspects/nvim/files/.config
          version: "0.14.0"
