# Based on: https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

name: ci

on:
  push:
    branches: [main, next, pu]
  pull_request:
    branches: [main, next, pu]

jobs:

  check-lockfile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionsx/prettier@v3
        with:
          # ******************************************************************
          # * NOTE: Keep these patterns up-to-date with bin/{check-,}format. *
          # ******************************************************************
          args: --list-different "**/*.{js,json,md,ts}" "*.{md,ts}"

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --allow-hidden --check .
          version: "0.18.1"
